version: "3.7"

services:
    crm_service_mongo:
        image: bitnami/mongodb
        restart: unless-stopped
        environment:
            - MONGODB_USERNAME=mongo
            - MONGODB_PASSWORD=mongo
            - MONGODB_DATABASE=crm-service-dev
            - ALLOW_EMPTY_PASSWORD=yes
            - MONGODB_ROOT_PASSWORD=mongo
        volumes:
            - ./.docker/crm_service_mongo:/data/db
        ports:
            - "27017:27017"
        networks:
            - crm_service_network
    crm_service:
        container_name: crm_service
        build:
            context: .
            target: dev
        restart: unless-stopped
        volumes:
            - ./src:/usr/src/app/src:rw
            - ./swagger.json:/usr/src/app/swagger.json:ro
        ports:
            - "3333:3333"
        environment:
            - PORT=3333
            - MONGO_URI=mongodb://root:mongo@crm_service_mongo:27017/crm-service-dev?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
            - NODE_ENV=development
        networks:
            - crm_service_network
    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9001"
        user: ${CURRENT_UID}
        environment:
            - MINIO_API_CORS_ALLOW_ORIGIN=*
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - './.docker/minio:/data'
        networks:
            - crm_service_network
networks:
    crm_service_network:
        driver: bridge
